title:            Planitude
description:      "Bon baisers d'ailleurs"
disqus_shortname: planitude

# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
baseurl:        'http://planitude.github.io/'
#baseurl:        ''
#baseurl:        'http://localhost:3000'
url:        	  ''

keywords: [blog, voyage, sac à dos]
cover_default: https://farm2.staticflickr.com/1620/24725894305_5b3287184a

# Owner/author information
owner:
  name:           Julien Kéravec
  avatar:         julien.jpg
  email:          jkeravec@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Awesome Dude, Awesome Life
  # Social networking links used in footer. Update and remove as you like.
  twitter:        hmfaysal
  facebook:       hmfaysal
  github:         hmfaysal
  instagram:      hmfaysal
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/u/0/102602916593522619858

# MapBox
mapbox:
  mapid: mapbox.emerald
  #mapid: mapbox://styles/planitude/cikpa3uzh00m6b5lwr5rr83sr
  maptoken: pk.eyJ1IjoicGxhbml0dWRlIiwiYSI6ImNpa21hcDJnbDAwN2t3OW00NHExNmJpZmsifQ.h19ybld8IuZGzPcx1Q84Yw

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-XXX
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Paris
future:      true
# highlighter: pygments
markdown:    kramdown

# Plugins
gems:             ["jekyll-sitemap", "jekyll-paginate"]

paginate:    2
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
#permalink: pretty
permalink:   /:categories/:year/:title.html

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  rooturl: '_posts'
  siteurl: 'http://hmfaysal.github.io/Notepad/'
  relativeLinks: 'http://hmfaysal.github.io/Notepad/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Engineering"
              value: engineering
            - name: "Physics"
              value: physics
            - name: "Psychology"
              value: psychology
            - name: "Interesting"
              value: interesting
            - name: "Web-Development"
              value: webdevelopment
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false


include:
  - ".htaccess"
  - "_pages"

exclude:
  - "assets/js/app.js"
  - "assets/scss/*.scss"
  - "assets/vendor/foundation-sites/"
  - "assets/vendor/jquery/"
  - "assets/vendor/motion-ui/"
  - "assets/vendor/phpmailer/**/*.html"
  - "assets/vendor/what-input/"
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulp"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"
